import Link from "next/link";
import { BarChart3, Bell, Boxes, CreditCard, FileText, Globe2, KeyRound, LayoutDashboard, MessageSquareText, PackageCheck, Palette, Receipt, Settings, ShoppingBag, Tag, Users, Webhook } from "lucide-react";
import { Logo } from "@/components/logo";
import { switchStoreAction } from "@/lib/dashboard-actions";

export const dashboardNav=[
 ["Overview","/dashboard",LayoutDashboard],["Orders","/dashboard/orders",Receipt],["Products","/dashboard/products",ShoppingBag],["Customers","/dashboard/customers",Users],["Reviews","/dashboard/reviews",MessageSquareText],["Analytics","/dashboard/analytics",BarChart3],["Storefront","/dashboard/storefront",Boxes],["Themes","/dashboard/themes",Palette],["Pages","/dashboard/pages",FileText],["Domains","/dashboard/domains",Globe2],["Coupons","/dashboard/coupons",Tag],["Payments","/dashboard/payments",CreditCard],["Fulfillment","/dashboard/fulfillment",PackageCheck],["Developers","/dashboard/developers",Webhook],["Settings","/dashboard/settings",Settings],["Billing","/dashboard/settings/billing",KeyRound],
] as const;
export function Sidebar({stores,activeId}:{stores:{id:string;name:string;slug:string}[];activeId?:string}){return <aside className="hidden h-screen w-64 shrink-0 border-r border-[#181818] bg-[#080808] lg:flex lg:flex-col"><div className="p-5"><Logo/></div>{stores.length>0&&<form action={switchStoreAction} className="px-3 pb-3"><label className="sr-only" htmlFor="store-switcher">Store</label><select id="store-switcher" name="storeId" defaultValue={activeId} className="text-sm">{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="mt-2 w-full rounded-md border border-sc-border px-2 py-1.5 text-xs text-sc-secondary">Switch store</button></form>}<nav className="flex-1 overflow-y-auto px-3 pb-4">{dashboardNav.map(([label,href,Icon])=><Link key={href} href={href} className="mb-1 flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-sc-secondary hover:bg-[#121212] hover:text-white"><Icon size={16}/>{label}</Link>)}</nav><div className="border-t border-[#181818] p-3"><Link href="/dashboard/notifications" className="flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-sc-secondary hover:bg-[#121212]"><Bell size={16}/>Notifications</Link></div></aside>}
