import Link from "next/link";
import { ArrowRight, Boxes, CreditCard, Gauge, Globe2, KeyRound, PackageCheck, Plug, Star } from "lucide-react";
import { Card } from "@/components/ui/card";
import { InteractiveHeroBackground } from "@/components/marketing/interactive-hero-background";

const features=[
  [PackageCheck,"Automatic fulfillment","Licenses, files, accounts, services, subscriptions and custom delivery behind one order pipeline.","digital-fulfillment"],
  [CreditCard,"Real payments","Stripe Checkout for customer payments and Stripe Billing for SellCore subscriptions.","payments-checkout"],
  [Globe2,"Your storefront","SellCore subdomains, custom domains, structured pages and configurable themes.","storefront-builder"],
  [Gauge,"Store analytics","Revenue, orders, conversion events, product views and customer activity from real events.","analytics-insights"],
  [Star,"Verified reviews","Purchase-aware reviews with moderation and stable-ID deduplication.","customer-trust"],
  [Plug,"Developer access","Scoped API keys, signed webhooks, delivery logs and retries.","developer-platform"],
];
export default function Home(){return <main>
<section className="relative overflow-hidden border-b border-[#181818]"><InteractiveHeroBackground/><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[1.05fr_.95fr] lg:py-32"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#321417] bg-[#120708]/90 px-3 py-1 text-xs text-[#ff9ca1] backdrop-blur"><span className="h-1.5 w-1.5 rounded-full bg-sc-red"/> Free plan included</div><h1 className="max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.05em] sm:text-6xl lg:text-7xl">Sell anything.<br/>Built around you.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-sc-secondary">Create a storefront, sell digital products and services, automate fulfillment and run the operation from one dashboard.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-lg bg-sc-red px-5 py-3 font-medium shadow-[0_12px_45px_rgba(229,9,20,.22)]">Start selling <ArrowRight size={17}/></Link><Link href="#platform" className="rounded-lg border border-sc-border bg-[#0b0b0b]/80 px-5 py-3 font-medium backdrop-blur">Explore the platform</Link></div></div><div className="rounded-2xl border border-[#2a2021] bg-[#080808]/75 p-3 shadow-2xl backdrop-blur-xl"><div className="rounded-xl border border-sc-border bg-[#0d0d0d]/90"><div className="flex items-center justify-between border-b border-sc-border p-4"><span className="text-sm font-medium">Operations</span><span className="text-xs text-sc-secondary">Live merchant workspace</span></div><div className="grid gap-3 p-4 sm:grid-cols-3">{[["Orders","Real-time"],["Fulfillment","Idempotent"],["Inventory","Reserved"]].map(([a,b])=><div key={a} className="rounded-lg border border-sc-border bg-[#111] p-4"><div className="text-xs text-sc-secondary">{a}</div><div className="mt-4 text-lg font-semibold">{b}</div></div>)}</div><div className="m-4 rounded-lg border border-sc-border"><div className="grid grid-cols-4 border-b border-sc-border px-4 py-3 text-xs text-sc-muted"><span>EVENT</span><span>STATE</span><span>TENANT</span><span>PIPELINE</span></div>{[["order.paid","verified","isolated","fulfill"],["review.created","pending","isolated","moderate"],["domain.verified","ready","isolated","route"]].map(r=><div key={r[0]} className="grid grid-cols-4 px-4 py-3 text-sm text-sc-secondary">{r.map((x,i)=><span key={i}>{x}</span>)}</div>)}</div></div></div></div></section>
<section id="platform" className="mx-auto max-w-7xl px-5 py-24"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div className="max-w-2xl"><p className="text-sm font-semibold text-sc-red">PLATFORM</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">The parts you need to operate a digital store.</h2></div><Link href="/features" className="text-sm font-medium text-[#ff8085]">Explore every feature →</Link></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,desc,slug])=><Link key={String(title)} href={`/features/${slug}`} className="block"><Card className="h-full p-6 transition hover:border-[#4a2427] hover:bg-[#130b0c]"><Icon size={22} className="text-sc-red"/><h3 className="mt-5 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-sc-secondary">{desc as string}</p><span className="mt-5 inline-block text-sm text-[#ff8085]">Learn more →</span></Card></Link>)}</div></section>
<section className="border-y border-[#181818] bg-[#080808]"><div className="mx-auto max-w-7xl px-5 py-20"><div className="max-w-2xl"><p className="text-sm font-semibold text-sc-red">FROM SETUP TO DELIVERY</p><h2 className="mt-3 text-3xl font-semibold">A store is more than a landing page.</h2><p className="mt-4 text-sc-secondary">SellCore connects presentation, checkout, fulfillment and operations so merchants do not have to stitch together the critical order path.</p></div><div className="mt-10 grid gap-4 md:grid-cols-4">{[["01","Build","Create products, variants and a storefront."],["02","Publish","Launch on a merchant subdomain or eligible custom domain."],["03","Sell","Validate carts, coupons and payment state on the server."],["04","Deliver","Issue inventory or track merchant-managed work."]].map(([number,title,copy])=><div key={number} className="rounded-xl border border-sc-border bg-sc-card p-5"><span className="text-xs font-semibold text-sc-red">{number}</span><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-sc-secondary">{copy}</p></div>)}</div></div></section>
<section className="border-b border-[#181818] bg-[#080808]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2"><div><Boxes className="text-sc-red"/><h2 className="mt-5 text-3xl font-semibold">More than license keys.</h2><p className="mt-4 max-w-xl text-sc-secondary">Sell licenses, private downloads, transferable account inventory, services, recurring products, generated deliveries or a custom fulfillment workflow.</p></div><div className="grid grid-cols-2 gap-3 text-sm">{["License pools","Digital files","Account inventory","Services","Subscriptions","Generated products","Custom delivery","Product variants"].map(x=><div key={x} className="rounded-lg border border-sc-border bg-sc-card px-4 py-3">{x}</div>)}</div></div></section>
<section className="mx-auto max-w-7xl px-5 py-24"><div className="rounded-2xl border border-[#3a1518] bg-[radial-gradient(circle_at_20%_20%,rgba(229,9,20,.18),transparent_35%),#0a0a0a] p-8 md:p-12"><KeyRound className="text-sc-red"/><h2 className="mt-5 text-3xl font-semibold">Start on Free. Keep the store real.</h2><p className="mt-3 max-w-2xl text-sc-secondary">Free is a permanent operating plan, not a timed demo. Paid plans increase limits and unlock capabilities such as domains, API access, webhooks and advanced analytics.</p><Link href="/pricing" className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-[#ff7a80]">See current plans <ArrowRight size={16}/></Link></div></section>
<section id="faq" className="mx-auto max-w-4xl px-5 pb-24"><h2 className="text-3xl font-semibold">FAQ</h2><div className="mt-8 divide-y divide-sc-border border-y border-sc-border">{[["Is Free a trial?","No. The Free plan is designed to operate a basic published store within configured limits."],["Does SellCore store card numbers?","No. Payment details are handled by the configured payment provider."],["Can stores use custom domains?","Yes, when the merchant plan enables custom domains and the domain verifies correctly."],["Can a plan be changed later?","Yes. Downgrades keep historical data and enforce the new limits going forward."]].map(([q,a])=><div key={q} className="py-5"><h3 className="font-medium">{q}</h3><p className="mt-2 text-sm leading-6 text-sc-secondary">{a}</p></div>)}</div></section>
</main>}
