"use server";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/auth/session";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";

export async function updatePlanAction(formData:FormData){await requireAdmin();const db=createSupabaseAdminClient();const id=z.string().uuid().parse(formData.get("planId"));const monthly=Math.round(Number(formData.get("monthlyPrice")||0)*100);const yearly=Math.round(Number(formData.get("yearlyPrice")||0)*100);await db.from("platform_plans").update({name:String(formData.get("name")),description:String(formData.get("description")||""),monthly_price_minor:monthly,yearly_price_minor:yearly,currency:String(formData.get("currency")||"USD").toUpperCase(),stripe_monthly_price_id:String(formData.get("stripeMonthlyPriceId")||"")||null,stripe_yearly_price_id:String(formData.get("stripeYearlyPriceId")||"")||null,is_active:formData.get("isActive")==="on",trial_days:Number(formData.get("trialDays")||0)}).eq("id",id);await db.from("plan_features").update({enabled:false}).eq("plan_id",id);for(const [key,value] of formData.entries()){if(key.startsWith("limit:")){const limitKey=key.slice(6);const n=value===""?null:Number(value);await db.from("plan_limits").upsert({plan_id:id,limit_key:limitKey,limit_value:n},{onConflict:"plan_id,limit_key"});}if(key.startsWith("feature:")){const featureKey=key.slice(8);await db.from("plan_features").upsert({plan_id:id,feature_key:featureKey,enabled:value==="on"},{onConflict:"plan_id,feature_key"});}}revalidatePath("/admin/plans");revalidatePath("/pricing");}
export async function createPlanAction(formData:FormData){await requireAdmin();const db=createSupabaseAdminClient();const {data,error}=await db.from("platform_plans").insert({slug:String(formData.get("slug")),name:String(formData.get("name")),description:String(formData.get("description")||""),is_free:false,is_active:true,monthly_price_minor:Math.round(Number(formData.get("monthlyPrice")||0)*100),yearly_price_minor:Math.round(Number(formData.get("yearlyPrice")||0)*100),currency:String(formData.get("currency")||"USD").toUpperCase(),sort_order:Number(formData.get("sortOrder")||50),trial_days:Number(formData.get("trialDays")||0)}).select("id").single();if(error||!data)throw new Error(error?.message??"PLAN_CREATE_FAILED");const limitKeys=["stores","products","orders_monthly","customers","storage_mb","api_requests_minute","webhook_deliveries_monthly","custom_domains","team_members","analytics_retention_days","digital_downloads_monthly","product_variants"];const featureKeys=["basic_storefront","basic_analytics","reviews","custom_domain","advanced_themes","advanced_analytics","api","webhooks","custom_branding","priority_support"];await db.from("plan_limits").insert(limitKeys.map(limit_key=>({plan_id:data.id,limit_key,limit_value:0})));await db.from("plan_features").insert(featureKeys.map(feature_key=>({plan_id:data.id,feature_key,enabled:false})));revalidatePath("/admin/plans");}
export async function updateAbuseReportAction(formData:FormData){await requireAdmin();const db=createSupabaseAdminClient();await db.from("abuse_reports").update({status:String(formData.get("status"))}).eq("id",String(formData.get("reportId")));revalidatePath("/admin/reports");}
export async function updatePlatformSettingAction(formData:FormData){const user=await requireAdmin();const db=createSupabaseAdminClient();const key=String(formData.get("key"));let value:unknown;try{value=JSON.parse(String(formData.get("value")));}catch{throw new Error("Value must be valid JSON");}await db.from("platform_settings").upsert({key,value,updated_by:user.id},{onConflict:"key"});revalidatePath("/admin/settings");}
export async function setUserRoleAction(formData:FormData){const admin=await requireAdmin();const userId=String(formData.get("userId"));if(userId===admin.id&&formData.get("role")!=="admin")throw new Error("Cannot remove your own admin access here.");const db=createSupabaseAdminClient();await db.from("users").update({platform_role:String(formData.get("role"))}).eq("id",userId);revalidatePath("/admin/merchants");}
