"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { resolveTxt } from "node:dns/promises";
import { requireMerchant } from "@/lib/auth/session";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { assertFeature, canCreateWithinLimit, getPlanFeatures } from "@/lib/usage/service";
import { encryptSecret, randomToken, sha256 } from "@/lib/crypto";
import { getStripe } from "@/lib/payments/stripe";
import { createStripeConnectOnboarding } from "@/lib/payments/connect";
import { createBillingCheckout, createBillingPortal } from "@/lib/payments/billing";
import { serverEnv } from "@/lib/env";

async function ownedStore(storeId:string,merchantId:string){const db=createSupabaseAdminClient(); const {data}=await db.from("stores").select("*").eq("id",storeId).eq("merchant_id",merchantId).maybeSingle(); if(!data)throw new Error("FORBIDDEN"); return {db,store:data};}

export async function publishStoreAction(formData:FormData){const {merchantId,user}=await requireMerchant();const id=String(formData.get("storeId"));const {db}=await ownedStore(id,merchantId);const status=String(formData.get("status"))==="published"?"published":"unpublished";await db.from("stores").update({status}).eq("id",id);await db.from("audit_logs").insert({merchant_id:merchantId,store_id:id,actor_user_id:user.id,action:`store.${status}`,resource_type:"store",resource_id:id});revalidatePath("/dashboard/storefront");}
export async function updateStoreAction(formData:FormData){const {merchantId,user}=await requireMerchant();const id=String(formData.get("storeId"));const {db}=await ownedStore(id,merchantId);await db.from("stores").update({name:String(formData.get("name")),description:String(formData.get("description")||""),default_currency:String(formData.get("currency")||"USD").toUpperCase()}).eq("id",id);await db.from("store_settings").upsert({store_id:id,title:String(formData.get("title")||formData.get("name")),meta_description:String(formData.get("metaDescription")||""),support_email:String(formData.get("supportEmail")||"")||null,verified_reviews_only:formData.get("verifiedReviewsOnly")==="on"},{onConflict:"store_id"});await db.from("audit_logs").insert({merchant_id:merchantId,store_id:id,actor_user_id:user.id,action:"settings.updated",resource_type:"store",resource_id:id});revalidatePath("/dashboard/settings");}

export async function selectThemeAction(formData:FormData){const {merchantId}=await requireMerchant();const storeId=String(formData.get("storeId"));const themeId=String(formData.get("themeId"));const {db}=await ownedStore(storeId,merchantId);const {data:theme}=await db.from("themes").select("*").eq("id",themeId).eq("is_active",true).single();if(!theme)throw new Error("THEME_NOT_FOUND");if(theme.is_advanced)await assertFeature(merchantId,"advanced_themes");await db.from("theme_settings").upsert({store_id:storeId,theme_id:theme.id,custom_theme_id:null,settings:theme.defaults},{onConflict:"store_id"});revalidatePath("/dashboard/themes");revalidatePath("/store");}
export async function updateThemeSettingsAction(formData:FormData){const {merchantId}=await requireMerchant();const storeId=String(formData.get("storeId"));const {db}=await ownedStore(storeId,merchantId);const {data:current}=await db.from("theme_settings").select("settings").eq("store_id",storeId).single();const settings={...(current?.settings??{}),accent:String(formData.get("accent")||"#E50914"),background:String(formData.get("background")||"#050505"),text:String(formData.get("text")||"#F5F5F5"),radius:String(formData.get("radius")||"8px"),font:String(formData.get("font")||"Manrope"),headerStyle:String(formData.get("headerStyle")||"standard"),cardStyle:String(formData.get("cardStyle")||"bordered"),layout:String(formData.get("layout")||"grid")};await db.from("theme_settings").update({settings}).eq("store_id",storeId);revalidatePath("/dashboard/themes");}

export async function createPageAction(formData:FormData){const {merchantId}=await requireMerchant();const storeId=String(formData.get("storeId"));const {db}=await ownedStore(storeId,merchantId);const title=String(formData.get("title"));const slug=String(formData.get("slug"));const body=String(formData.get("body")||"");await db.from("pages").insert({store_id:storeId,title,slug,content:[{type:"rich_text",text:body}],status:String(formData.get("status")||"draft")});revalidatePath("/dashboard/pages");}
export async function deletePageAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("pageId"));const db=createSupabaseAdminClient();const {data}=await db.from("pages").select("id,store_id,stores!inner(merchant_id)").eq("id",id).eq("stores.merchant_id",merchantId).maybeSingle();if(!data)throw new Error("FORBIDDEN");await db.from("pages").delete().eq("id",id);revalidatePath("/dashboard/pages");}

export async function createCouponAction(formData:FormData){const {merchantId}=await requireMerchant();const storeId=String(formData.get("storeId"));const {db}=await ownedStore(storeId,merchantId);const type=String(formData.get("discountType"));const raw=Number(formData.get("discountValue"));const value=type==="percent"?Math.round(raw*100):Math.round(raw*100);await db.from("coupons").insert({store_id:storeId,code:String(formData.get("code")).toUpperCase(),discount_type:type,discount_value:value,currency:String(formData.get("currency")||"USD"),expires_at:String(formData.get("expiresAt")||"")||null,usage_limit:formData.get("usageLimit")?Number(formData.get("usageLimit")):null,per_customer_limit:formData.get("perCustomerLimit")?Number(formData.get("perCustomerLimit")):null,minimum_order_minor:formData.get("minimumOrder")?Math.round(Number(formData.get("minimumOrder"))*100):null,active:true});revalidatePath("/dashboard/coupons");}
export async function toggleCouponAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("couponId"));const db=createSupabaseAdminClient();const {data}=await db.from("coupons").select("id,active,stores!inner(merchant_id)").eq("id",id).eq("stores.merchant_id",merchantId).single();if(!data)throw new Error("COUPON_NOT_FOUND");await db.from("coupons").update({active:!data.active}).eq("id",id);revalidatePath("/dashboard/coupons");}

export async function moderateReviewAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("reviewId"));const status=String(formData.get("status"));if(!["approved","hidden","rejected"].includes(status))throw new Error("INVALID_STATUS");const db=createSupabaseAdminClient();const {data}=await db.from("reviews").select("id,store_id,stores!inner(merchant_id)").eq("id",id).eq("stores.merchant_id",merchantId).maybeSingle();if(!data)throw new Error("FORBIDDEN");await db.from("reviews").update({status,merchant_response:String(formData.get("response")||"")||null}).eq("id",id);revalidatePath("/dashboard/reviews");revalidatePath("/store");}

export async function updateServiceStatusAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("fulfillmentId"));const status=String(formData.get("status"));if(!["pending","paid","in_progress","awaiting_customer","completed","cancelled","refunded"].includes(status))throw new Error("INVALID_STATUS");const db=createSupabaseAdminClient();const {data}=await db.from("service_fulfillments").select("id,order_items!inner(orders!inner(store_id,stores!inner(merchant_id)))").eq("id",id).eq("order_items.orders.stores.merchant_id",merchantId).maybeSingle();if(!data)throw new Error("FORBIDDEN");await db.from("service_fulfillments").update({status,merchant_notes:String(formData.get("notes")||"")||null}).eq("id",id);revalidatePath("/dashboard/fulfillment");}

export async function connectStripeAction(formData:FormData){const {merchantId}=await requireMerchant();const url=await createStripeConnectOnboarding(String(formData.get("storeId")),merchantId);redirect(url);}

export async function refundOrderAction(formData:FormData){const {merchantId,user}=await requireMerchant();const orderId=String(formData.get("orderId"));const db=createSupabaseAdminClient();const {data:order}=await db.from("orders").select("*,stores!inner(merchant_id)").eq("id",orderId).eq("stores.merchant_id",merchantId).single();if(!order||order.payment_status!=="paid")throw new Error("ORDER_NOT_REFUNDABLE");const {data:account}=await db.from("payment_accounts").select("provider_account_id").eq("store_id",order.store_id).eq("provider","stripe").single();if(!account||!order.payment_provider_payment_id)throw new Error("PAYMENT_REFERENCE_MISSING");await getStripe().refunds.create({payment_intent:order.payment_provider_payment_id},{stripeAccount:account.provider_account_id});await db.from("orders").update({payment_status:"refunded",fulfillment_status:"refunded"}).eq("id",orderId);await db.from("audit_logs").insert({merchant_id:merchantId,store_id:order.store_id,actor_user_id:user.id,action:"order.refunded",resource_type:"order",resource_id:orderId});revalidatePath(`/dashboard/orders/${orderId}`);}

export async function createDomainAction(formData:FormData){const {merchantId}=await requireMerchant();await assertFeature(merchantId,"custom_domain");const storeId=String(formData.get("storeId"));const {db}=await ownedStore(storeId,merchantId);const {count}=await db.from("domains").select("id",{count:"exact",head:true}).eq("store_id",storeId);const cap=await canCreateWithinLimit(merchantId,"custom_domains",count??0);if(!cap.allowed)throw new Error("PLAN_LIMIT:custom_domains");const hostname=String(formData.get("hostname")).toLowerCase().replace(/^https?:\/\//,"").split("/")[0].replace(/\.$/,"");if(!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i.test(hostname))throw new Error("INVALID_HOSTNAME");await db.from("domains").insert({store_id:storeId,hostname});revalidatePath("/dashboard/domains");}
export async function verifyDomainAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("domainId"));const db=createSupabaseAdminClient();const {data:domain}=await db.from("domains").select("*,stores!inner(merchant_id)").eq("id",id).eq("stores.merchant_id",merchantId).single();const records=await resolveTxt(`_sellcore.${domain.hostname}`).catch(()=>[]);const flattened=records.map(parts=>parts.join(""));if(!flattened.includes(domain.verification_token))throw new Error("DNS_VERIFICATION_NOT_FOUND");await db.from("domains").update({status:"verified",verified_at:new Date().toISOString()}).eq("id",id);revalidatePath("/dashboard/domains");}

export async function createApiKeyAction(formData:FormData){const {merchantId,user}=await requireMerchant();await assertFeature(merchantId,"api");const raw=randomToken("sc_live_");const scopes=String(formData.get("scopes")||"products:read,orders:read").split(",").map(x=>x.trim()).filter(Boolean);const db=createSupabaseAdminClient();await db.from("api_keys").insert({merchant_id:merchantId,name:String(formData.get("name")||"API key"),key_prefix:raw.slice(0,14),key_hash:sha256(raw),scopes,created_by:user.id});return {key:raw};}
export async function revokeApiKeyAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("keyId"));const db=createSupabaseAdminClient();await db.from("api_keys").update({revoked_at:new Date().toISOString()}).eq("id",id).eq("merchant_id",merchantId);revalidatePath("/dashboard/developers");}

export async function createWebhookAction(formData:FormData){const {merchantId}=await requireMerchant();await assertFeature(merchantId,"webhooks");const raw=randomToken("whsec_");const url=new URL(String(formData.get("url")));if(!["https:"].includes(url.protocol)&&process.env.NODE_ENV==="production")throw new Error("WEBHOOK_HTTPS_REQUIRED");const events=String(formData.get("events")||"").split(",").map(x=>x.trim()).filter(Boolean);const db=createSupabaseAdminClient();await db.from("webhooks").insert({merchant_id:merchantId,url:url.toString(),events,secret_hash:sha256(raw),encrypted_secret:encryptSecret(raw),active:true});return {secret:raw};}
export async function toggleWebhookAction(formData:FormData){const {merchantId}=await requireMerchant();const id=String(formData.get("webhookId"));const db=createSupabaseAdminClient();const {data}=await db.from("webhooks").select("active").eq("id",id).eq("merchant_id",merchantId).single();if(!data)throw new Error("WEBHOOK_NOT_FOUND");await db.from("webhooks").update({active:!data.active}).eq("id",id);revalidatePath("/dashboard/developers");}

export async function billingCheckoutAction(formData:FormData){const {merchantId}=await requireMerchant();const planId=String(formData.get("planId"));const url=await createBillingCheckout(merchantId,planId,"monthly");redirect(url);}
export async function billingPortalAction(){const {merchantId}=await requireMerchant();const url=await createBillingPortal(merchantId);redirect(url);}
export async function downgradeToFreeAction(){const {merchantId}=await requireMerchant();const db=createSupabaseAdminClient();const [{data:sub},{data:free}]=await Promise.all([db.from("merchant_subscriptions").select("*").eq("merchant_id",merchantId).single(),db.from("platform_plans").select("id").eq("is_free",true).eq("is_active",true).single()]);if(!free)throw new Error("FREE_PLAN_NOT_CONFIGURED");if(sub?.stripe_subscription_id)await getStripe().subscriptions.cancel(sub.stripe_subscription_id);await db.from("merchant_subscriptions").upsert({merchant_id:merchantId,plan_id:free.id,status:"free",billing_interval:"none",stripe_subscription_id:null,stripe_price_id:null,current_period_start:null,current_period_end:null,cancel_at_period_end:false},{onConflict:"merchant_id"});revalidatePath("/dashboard/settings/billing");}

export async function addTeamMemberAction(formData:FormData){const {merchantId}=await requireMerchant();const cap=await canCreateWithinLimit(merchantId,"team_members");if(!cap.allowed)throw new Error("PLAN_LIMIT:team_members");const email=String(formData.get("email")).toLowerCase();const role=String(formData.get("role")||"staff");const db=createSupabaseAdminClient();const {data:user}=await db.from("users").select("id").eq("email",email).maybeSingle();if(!user)throw new Error("User must create a SellCore account before being added.");await db.from("merchant_members").insert({merchant_id:merchantId,user_id:user.id,role});revalidatePath("/dashboard/settings");}

export async function platformBaseDomain(){return serverEnv().NEXT_PUBLIC_PLATFORM_DOMAIN;}
export async function getFeatureMap(){const {merchantId}=await requireMerchant();return getPlanFeatures(merchantId);}

export async function cancelPlatformSubscriptionAction(){const {merchantId}=await requireMerchant();const db=createSupabaseAdminClient();const {data:sub}=await db.from("merchant_subscriptions").select("stripe_subscription_id").eq("merchant_id",merchantId).single();if(!sub?.stripe_subscription_id)throw new Error("NO_ACTIVE_SUBSCRIPTION");await getStripe().subscriptions.update(sub.stripe_subscription_id,{cancel_at_period_end:true});await db.from("merchant_subscriptions").update({cancel_at_period_end:true}).eq("merchant_id",merchantId);revalidatePath("/dashboard/settings/billing");}
export async function reactivatePlatformSubscriptionAction(){const {merchantId}=await requireMerchant();const db=createSupabaseAdminClient();const {data:sub}=await db.from("merchant_subscriptions").select("stripe_subscription_id").eq("merchant_id",merchantId).single();if(!sub?.stripe_subscription_id)throw new Error("NO_ACTIVE_SUBSCRIPTION");await getStripe().subscriptions.update(sub.stripe_subscription_id,{cancel_at_period_end:false});await db.from("merchant_subscriptions").update({cancel_at_period_end:false}).eq("merchant_id",merchantId);revalidatePath("/dashboard/settings/billing");}
