"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/auth/session";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { z } from "zod";
import { enqueueWebhookEvent } from "@/lib/webhooks/outgoing";

const schema=z.object({productId:z.string().uuid(),rating:z.coerce.number().int().min(1).max(5),reviewText:z.string().trim().min(3).max(5000)});
export async function submitReviewAction(formData:FormData){const user=await requireUser("/account");const input=schema.parse({productId:formData.get("productId"),rating:formData.get("rating"),reviewText:formData.get("reviewText")});const db=createSupabaseAdminClient();const {data:p}=await db.from("products").select("id,slug,store_id,stores!inner(slug,merchant_id),store_settings!inner(verified_reviews_only)").eq("id",input.productId).single();if(!p)throw new Error("PRODUCT_NOT_FOUND");const {data:profile}=await db.from("users").select("email").eq("id",user.id).single();if(!profile?.email)throw new Error("EMAIL_REQUIRED");await db.from("customers").update({auth_user_id:user.id}).eq("store_id",p.store_id).ilike("email",profile.email).is("auth_user_id",null);const {data:c}=await db.from("customers").select("id").eq("store_id",p.store_id).ilike("email",profile.email).maybeSingle();if(!c)throw new Error("No customer record for this store. Purchase first.");const {data:item}=await db.from("order_items").select("id,orders!inner(customer_id,payment_status)").eq("product_id",p.id).eq("orders.customer_id",c.id).eq("orders.payment_status","paid").order("id").limit(1).maybeSingle();const settings=Array.isArray(p.store_settings)?p.store_settings[0]:p.store_settings;if(settings?.verified_reviews_only&&!item)throw new Error("VERIFIED_PURCHASE_REQUIRED");const {error}=await db.from("reviews").upsert({store_id:p.store_id,product_id:p.id,customer_id:c.id,order_item_id:item?.id??null,rating:input.rating,review_text:input.reviewText,verified_purchase:Boolean(item),status:"pending"},{onConflict:"product_id,customer_id,order_item_id"});if(error)throw new Error(error.message);const stores=Array.isArray(p.stores)?p.stores[0]:p.stores;await db.from("notifications").insert({merchant_id:stores.merchant_id,store_id:p.store_id,type:"review.created",title:"New review",body:`A ${input.rating}/5 review is awaiting moderation.`,data:{product_id:p.id}});await enqueueWebhookEvent(stores.merchant_id,"review.created",{product_id:p.id,store_id:p.store_id,rating:input.rating});revalidatePath(`/store/${stores.slug}/product/${p.slug}`);revalidatePath("/account");}
