import { NextResponse } from "next/server";
import Stripe from "stripe";
import { getStripe } from "@/lib/payments/stripe";
import { serverEnv } from "@/lib/env";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export const runtime="nodejs";
function period(sub:Stripe.Subscription){const s=sub as unknown as {current_period_start?:number;current_period_end?:number;items?:{data?:{current_period_start?:number;current_period_end?:number}[]}};const item=s.items?.data?.[0];return {start:s.current_period_start??item?.current_period_start,end:s.current_period_end??item?.current_period_end};}
function mapStatus(s:string){return ["trialing","active","past_due","canceled","unpaid","incomplete"].includes(s)?s:"incomplete";}
async function syncSubscription(sub:Stripe.Subscription){const merchantId=sub.metadata.merchant_id;const planId=sub.metadata.plan_id;if(!merchantId||!planId)return;const db=createSupabaseAdminClient();const p=period(sub);await db.from("merchant_subscriptions").upsert({merchant_id:merchantId,plan_id:planId,status:mapStatus(sub.status),billing_interval:sub.metadata.interval==="yearly"?"yearly":"monthly",stripe_subscription_id:sub.id,stripe_price_id:sub.items.data[0]?.price.id??null,current_period_start:p.start?new Date(p.start*1000).toISOString():null,current_period_end:p.end?new Date(p.end*1000).toISOString():null,cancel_at_period_end:sub.cancel_at_period_end,canceled_at:sub.canceled_at?new Date(sub.canceled_at*1000).toISOString():null},{onConflict:"merchant_id"});}
export async function POST(req:Request){const secret=serverEnv().STRIPE_PLATFORM_WEBHOOK_SECRET;if(!secret)return NextResponse.json({error:"Webhook not configured"},{status:503});const sig=req.headers.get("stripe-signature");if(!sig)return NextResponse.json({error:"Missing signature"},{status:400});let event:Stripe.Event;try{event=getStripe().webhooks.constructEvent(await req.text(),sig,secret);}catch{return NextResponse.json({error:"Invalid signature"},{status:400});}try{if(event.type==="checkout.session.completed"){const s=event.data.object as Stripe.Checkout.Session;const subId=typeof s.subscription==="string"?s.subscription:s.subscription?.id;if(subId)await syncSubscription(await getStripe().subscriptions.retrieve(subId));}else if(event.type==="customer.subscription.updated"||event.type==="customer.subscription.created"){await syncSubscription(event.data.object as Stripe.Subscription);}else if(event.type==="customer.subscription.deleted"){const sub=event.data.object as Stripe.Subscription;const merchantId=sub.metadata.merchant_id;if(merchantId){const db=createSupabaseAdminClient();const {data:free}=await db.from("platform_plans").select("id").eq("is_free",true).eq("is_active",true).single();if(free)await db.from("merchant_subscriptions").upsert({merchant_id:merchantId,plan_id:free.id,status:"free",billing_interval:"none",stripe_subscription_id:null,stripe_price_id:null,cancel_at_period_end:false},{onConflict:"merchant_id"});}}else if(event.type==="invoice.payment_failed"){const invoice=event.data.object as Stripe.Invoice;const customerId=typeof invoice.customer==="string"?invoice.customer:invoice.customer?.id;if(customerId){const db=createSupabaseAdminClient();const {data:m}=await db.from("merchants").select("id").eq("stripe_customer_id",customerId).maybeSingle();if(m){await db.from("merchant_subscriptions").update({status:"past_due"}).eq("merchant_id",m.id);await db.from("notifications").insert({merchant_id:m.id,type:"subscription.issue",title:"Platform payment failed",body:"Update billing details in the Stripe billing portal."});}}}return NextResponse.json({received:true});}catch(error){console.error("Stripe platform webhook error",error instanceof Error?error.message:"unknown");return NextResponse.json({error:"Webhook processing failed"},{status:500});}}
